# serverless.yml

service: demo-vehicles-backend

custom: # add these two lines
  env: ${file(env.json)} # reference the env.json file

provider:
  name: aws
  runtime: nodejs14.x
  httpApi:
    cors:
      allowedOrigins:
        - "*"
  stage: dev
  region: eu-central-1
  environment: # add environment property
    CACHE_TTL: ${self:custom.env.CACHE_TTL} 
    DEMO_VEHICLES_THIRDPARTY_API: ${self:custom.env.DEMO_VEHICLES_THIRDPARTY_API} 
    RETRY_LIMITS: ${self:custom.env.RETRY_LIMITS} 
    RETRY_DELAY: ${self:custom.env.RETRY_DELAY} 
    # reference the NODE_ENV from the secrets.json file

functions:
  app:
    handler: app.server # reference the file and exported method
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true